### ISSUE TITLE
Error - Error on writing

### ISSUE THREAD

**Issue by epac-tom** [BenjamimKrug/FullSerialMonitor#2]
Running 1.0.2 I loaded up the tool to have a play with but have found a error that requires killing the program from task manager.

Open the program, select and connect to a port. Open the sequence, added a packet, selected Send Sequence, I don't see anything in either window - not sure if I should. Then select Disconnect in the main window. I then get a Error window, Error on writing. Selecting ok just keeps popping up the same error.
I have to kill it with task manager to close it.

**Comment by BenjamimKrug** [comment]
If you click on save before clicking on send sequence does the issue still
happen? For the sequence to be sent it must have been saved. That might be
the cause.
But I think I'll change that in the future to avoid this kind of situation.

Em ter., 9 de abr. de 2024 11:50, epac-tom ***@***.***>
escreveu:

**Comment by epac-tom** [comment]
Doesn't appear to matter whether it is saved or not.
Infact I must have saved it as when I reopen after killing it, the packet is still there.
Crashes on that packet, and if I create a new packet and select send, without saving, same behaviour.

**Comment by BenjamimKrug** [comment]
Did you install it on a protected folder or something of the sort? Like in
the Program Files folder? It might be having an issue with writing the
files due to a lack of access permission.
Also, what OS are you using it on? For now the only OS I've tested on are
Windows 10 and 11, so that might be another problem.

Em ter., 9 de abr. de 2024 às 12:02, epac-tom ***@***.***>
escreveu:

**Comment by epac-tom** [comment]
I downloaded the zip and extracted the contents to a folder on my desktop. Running Windows 10

**Comment by BenjamimKrug** [comment]
Do the other features work correctly? Is it only with the packet sequencer?
Can you open the devtools and see if there are any warnings or error
messages?
Also, if we do not manage to solve the issue via message, would it be
possible for us to get on a discord/meet/zoom call to try and see if there
are any clues to the problem?

Em ter., 9 de abr. de 2024 às 12:17, epac-tom ***@***.***>
escreveu:

**Comment by epac-tom** [comment]
I'm trying other things out, basic sending receiving seems to be ok, I did notice this when trying to recreate this issue again:
![image](https://github.com/BenjamimKrug/FullSerialMonitor/assets/63097910/e36c8bc0-85b6-4c44-b357-5cd858e2cfa8)

**Comment by BenjamimKrug** [comment]
Can you try changing the configuration, saving it and opening the program
again? Like the theme or any of the log configurations just to be sure that
it is managing to at least save the config file.

The issue from the picture usually happens when it fails to save the
sequence file and then tries to send the sequence, but from what you've
described it did save the sequence. That's very odd.

Em ter., 9 de abr. de 2024 às 12:34, epac-tom ***@***.***>
escreveu:

**Comment by epac-tom** [comment]
I think I've gone down off track here, it looks like this is only occuring on one device, which I suspect is contributing to the issue.
I'm going to close the issue because this device does so some unusual things when the port is opened/closed and I suspect it's that rather than this program.

**Comment by BenjamimKrug** [comment]
Oh, ok, but if it appears again be sure to tell me, as I want it to work on
everything eventually.

Em ter., 9 de abr. de 2024 às 13:30, epac-tom ***@***.***>
escreveu:

**Comment by epac-tom** [comment]
Will do. I'm not 100% but I'm pretty sure this device reboots on the COM port disconnecting, so I suspect it something odd happening when that occurs. If you're interested it's [this device](https://www.nordicsemi.com/Products/Development-hardware/nRF52840-Dongle), I hadn't realised it was when I was opening/closing that particular device that the error was occuring.

**Comment by BenjamimKrug** [comment]
Oh, I've dealt with this device before and it can be quite a pain to use
it, but never tried it on my serial monitor, might be an issue

Em ter., 9 de abr. de 2024 às 13:36, epac-tom ***@***.***>
escreveu:
